name: note_app
description: Une application de prise de notes en Markdown

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI et icônes
  cupertino_icons: ^1.0.6
  
  # Stockage local
  shared_preferences: ^2.2.2
  
  # Markdown
  flutter_markdown: ^0.6.18
  markdown: ^7.1.1
  
  # Utilitaires
  intl: ^0.18.1
  
  # State management
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "assets/images/icon_foreground.png"
